const services=["Signature Facial","Glow Manicure","Relaxation Massage","Bridal Beauty"];
const testimonials=["Beautiful service from start to finish. I left feeling amazing.","Professional, welcoming and exactly what I needed.","The booking process was easy and the team was fantastic."];
export default function Home(){const wa="https://wa.me/233000000000";return <main>
<header className="nav"><a className="logo" href="#home">Luxe<span>Glow</span></a><nav><a href="#about">About</a><a href="#services">Services</a><a href="#gallery">Gallery</a><a href="#contact">Contact</a></nav><a className="pill dark" href={wa}>Book Now</a></header>
<section id="home" className="hero"><div><p className="eyebrow">BEAUTY • WELLNESS • CONFIDENCE</p><h1>Look good.<br/><i>Feel your best.</i></h1><p className="lead">Premium beauty and wellness treatments designed to help you relax, refresh and feel confident.</p><div className="actions"><a className="pill dark" href="#contact">Book an Appointment</a><a className="pill outline" href={wa}>Chat on WhatsApp</a></div></div><div className="heroImage"><span>YOUR HERO IMAGE</span></div></section>
<section id="about" className="section split"><div><p className="eyebrow">WELCOME</p><h2>A little time for you can make a big difference.</h2></div><div><p className="muted big">At LuxeGlow, every visit is designed around you. From relaxing treatments to polished beauty services, our goal is to create an experience that feels personal, professional and effortless.</p><a className="link" href="#contact">Discover more →</a></div></section>
<section id="services" className="section soft"><div className="sectionHead"><div><p className="eyebrow">OUR SERVICES</p><h2>Designed around your glow.</h2></div><p className="muted">Replace these cards with the client's real services and prices.</p></div><div className="cards">{services.map((s,i)=><article className="card" key={s}><small>0{i+1}</small><h3>{s}</h3><p className="muted">A premium treatment tailored to your needs.</p><a className="link" href="#contact">Enquire →</a></article>)}</div></section>
<section className="section reasons"><div><p className="eyebrow">WHY CHOOSE US</p><h2>Professional care. Personal attention.</h2></div><div className="reasonGrid">{["Experienced team","Beautiful experience","Easy booking","Made for you"].map((x,i)=><div key={x}><b>0{i+1}</b><h3>{x}</h3><p className="muted">Friendly professionals focused on quality and your experience.</p></div>)}</div></section>
<section id="gallery" className="section soft"><div className="sectionHead"><div><p className="eyebrow">GALLERY</p><h2>See the experience.</h2></div><p className="muted">Swap these placeholders for the client's best photos.</p></div><div className="gallery">{[1,2,3,4,5,6].map(n=><div className="galleryItem" key={n}>PHOTO 0{n}</div>)}</div></section>
<section className="section darkSection"><p className="eyebrow">CLIENT LOVE</p><h2>What our clients say.</h2><div className="quotes">{testimonials.map((t,i)=><figure key={i}><blockquote>“{t}”</blockquote><figcaption>Client {i+1}</figcaption></figure>)}</div></section>
<section id="contact" className="section contact"><div><p className="eyebrow">READY WHEN YOU ARE</p><h2>Let’s plan your next visit.</h2><p className="muted big">Replace the details below with the client's real contact information.</p></div><div className="contactBox"><p><b>PHONE</b><br/>+233 00 000 0000</p><p><b>LOCATION</b><br/>Accra, Ghana</p><p><b>HOURS</b><br/>Mon–Sat, 9:00 AM–6:00 PM</p><a className="pill dark" href={wa}>Message on WhatsApp</a></div></section>
<footer><div className="logo">Luxe<span>Glow</span></div><p>© 2026 LuxeGlow Beauty & Spa. Demo template.</p></footer><a className="floating" href={wa}>WhatsApp</a></main>}
